### ISSUE TITLE
Incorrect redirect for STK screenshots

### ISSUE THREAD

**Issue by AsciiWolf** [supertuxkart/stk-website#7]
I use these screenshots in AppStream metadata for my Linux (Flatpak) package of STK:

https://supertuxkart.net/images/1/1f/Supertuxkart-0.9.2-screenshot-1.jpg
https://supertuxkart.net/images/2/2a/Supertuxkart-0.9.2-screenshot-2.jpg
https://supertuxkart.net/images/8/83/Supertuxkart-0.9.2-screenshot-3.jpg

However, they stopped working. They now redirect directly to this GitHub repository and it looks like that they do not exist anymore.

**Comment by Benau** [comment]
Please use the new link in https://supertuxkart.net/Gallery

**Comment by Benau** [comment]
try this one https://github.com/supertuxkart/stk-code/blob/master/data/supertuxkart.appdata.xml

**Comment by AsciiWolf** [comment]
Thanks, but the main problem here is that the old links are in STK 1.3 AppData file and so the AppData will be broken everywhere (unless patched manually) until new STK is released. This is really far from ideal and shouldn't have happened.

**Comment by Benau** [comment]
New stk release may come within a month

Fixing that would require bloating this repo with duplicated file which I would like to avoid.. (supertuxkart.net is hosted using github page)

**Comment by AsciiWolf** [comment]
Ah, fair enough. :-) Thanks! I will fix it in a downstream patch for now.

**Comment by JakobDev** [comment]
For the future: Please keep links working. That can cause problems when building the App. Or place at least redirects. See [Cool URIs don't change](https://www.w3.org/Provider/Style/URI.html).
